service: serverless-prisma

frameworkVersion: '>=1.9.0 <2.0.0'

custom:
  stage: ${opt:stage, self:provider.stage}
  webpack:
    includeModules: true
    packager: yarn
    webpackConfig: ./webpack.config.js

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  region: us-east-1
  runtime: nodejs8.10
  deploymentBucket: ${env:ARTIFACTS_BUCKET}
  environment:
    PRISMA_DEBUG: ${env:PRISMA_DEBUG}
    PRISMA_ENDPOINT: ${env:PRISMA_ENDPOINT}
    PRISMA_SECRET: ${env:PRISMA_SECRET}
    PRISMA_SERVICE: ${env:PRISMA_SERVICE}

functions:
  graphql:
    name: serverless-prisma-${self:custom.stage}
    handler: src/graphql.handler
    events:
      - http:
          cors: true
          integration: lambda-proxy
          method: get
          path: /
      - http:
          cors: true
          integration: lambda-proxy
          method: post
          path: /

resources:
  Resources:
    ApiGatewayBasePathMapping:
      DependsOn: ApiGatewayDomainName
      Type: AWS::ApiGateway::BasePathMapping
      Properties:
        BasePath: ''
        DomainName: ${env:API_DOMAIN_NAME}
        RestApiId:
          Ref: ApiGatewayRestApi # created by serverless, check the stack's resources
        Stage: ${self:custom.stage}

    ApiGatewayDomainName:
      Type: AWS::ApiGateway::DomainName
      Properties:
        CertificateArn:	${env:API_SSL_CERT_ARN}
        DomainName: ${env:API_DOMAIN_NAME}

    ApiGatewayRecordSetGroup:
      Type: AWS::Route53::RecordSetGroup
      Properties:
        HostedZoneName: ${env:API_HOSTED_ZONE}.
        RecordSets:
          - Name: ${env:API_DOMAIN_NAME}.
            Type: A
            AliasTarget:
              DNSName: {'Fn::GetAtt': ApiGatewayDomainName.DistributionDomainName}
              HostedZoneId: Z2FDTNDATAQYW2
          - Name: ${env:API_DOMAIN_NAME}.
            Type: AAAA
            AliasTarget:
              DNSName: {'Fn::GetAtt': ApiGatewayDomainName.DistributionDomainName}
              HostedZoneId: Z2FDTNDATAQYW2
