service: serverless-prisma

frameworkVersion: ">=1.9.0 <2.0.0"

custom:
  stage: ${opt:stage, self:provider.stage}
  webpack:
    includeModules: true
    packager: yarn
    webpackConfig: ./webpack.config.js

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  deploymentBucket: ${env:ARTIFACTS_BUCKET}
  environment:
    EXAMPLE_DEBUG: "something something"

functions:
  graphql:
    name: serverless-prisma-${self:custom.stage}
    handler: src/graphql.handler
    events:
      - http:
          cors: true
          integration: lambda-proxy
          method: get
          path: /
      - http:
          cors: true
          integration: lambda-proxy
          method: post
          path: /
  playground:
    name: serverless-prisma-playground-${self:custom.stage}
    handler: src/playground.handler
    events:
      - http:
          cors: true
          integration: lambda-proxy
          method: get
          path: /playground
